title: Yang's Personal Web
email: yplsw90@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. I am a computational chemist focusing on molecular dynamics and AI drug design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://YangChemE.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  YangChemE

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

# Minimal Mistakes settings
author:
  name: Yang
  avatar: "/assets/images/avatar.png"
  bio: "Computational chemist focusing on molecular dynamics and AI drug design."
  location: "Your Location"
  email: "yplsw90@outlook.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/YangChemE"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/jekyllrb"

# Navigation links
nav:
  - text: "Home"
    url: "/"
  - text: "About"
    url: "/about/"
  - text: "Research"
    url: "/research/"
  - text: "Publications"
    url: "/publications/"
  - text: "Projects"
    url: "/projects/"
  - text: "Contact"
    url: "/contact/"

sass:
  load_paths:
    - _sass