# Site settings
title: Yang Wang | Personal Website
email: your.email@example.com
description: >-
  Personal website of Yang Wang, Chemical Engineering Researcher exploring 
  computational methods for molecular dynamics and chemical interactions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yangcheme.github.io" # the base hostname & protocol for your site
github_username: YangChemE
linkedin_username: yourprofile
twitter_username: yourhandle
google_scholar: YourID
formspree_id: xxxxxxxxxxxx # Replace with your actual Formspree form ID

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:name
  research:
    output: true
    permalink: /:collection/:name

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Minimal Mistakes settings
author:
  name: Yang
  avatar: "/assets/images/avatar.png"
  bio: "Computational chemist focusing on molecular dynamics and AI drug design."
  location: "Your Location"
  email: "yplsw90@outlook.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/YangChemE"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/jekyllrb"

# Navigation links
nav:
  - text: "Home"
    url: "/"
  - text: "About"
    url: "/about/"
  - text: "Research"
    url: "/research/"
  - text: "Publications"
    url: "/publications/"
  - text: "Projects"
    url: "/projects/"
  - text: "Contact"
    url: "/contact/"

sass:
  load_paths:
    - _sass